export const fontFamilyConfig = [
    { label: 'Arial', value: 'Arial' },
    { label: 'Bubblegum Sans', value: 'Bubblegum Sans' },
    { label: 'Comic Neue', value: 'Comic Neue' },
    { label: 'Consolas', value: 'Consolas' },
    { label: 'Courier New', value: 'Courier New' },
    { label: 'Fredoka One', value: 'Fredoka One' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Helvetica', value: 'Helvetica' },
    { label: 'Monaco', value: 'Monaco' },
    { label: 'Palatino', value: 'Palatino' },
    { label: 'Patrick Hand', value: 'Patrick Hand' },
    { label: 'Poppins', value: 'Poppins' },
    { label: 'Tahoma', value: 'Tahoma' },
    { label: 'Times New Roman', value: 'Times New Roman' },
    { label: 'Trebuchet MS', value: 'Trebuchet MS' },
    { label: 'Verdana', value: 'Verdana' },
];
